### ISSUE TITLE
A small question about this project

### ISSUE THREAD

**Issue by CHMimilanlan** [gxlover0625/VLMInference#1]
Is the author of this project DA SHUAI GE?

**Comment by CHMimilanlan** [comment]
I know, it is a small question relating to Hui's laugh.

**Comment by gxlover0625** [comment]
> Is the author of this project DA SHUAI GE?

Thank you for your contribution to the community. Here is the answer: I am just a simple developer whose interests mainly focus on the multi-modal large language model. With the help of community, this project will be enriched and have more fantanstic features!

**Comment by CHMimilanlan** [comment]
Awsome!

**Comment by CHMimilanlan** [comment]
> > Is the author of this project DA SHUAI GE?
> 
> Thank you for your contribution to the community. Here is the answer: I am just a simple developer whose interests mainly focus on the multi-modal large language model. With the help of community, this project will be enriched and have more fantanstic features!

Awesome!
